language: cpp

compiler:
  - clang
  - gcc

before_install:
  - sudo add-apt-repository ppa:boost-latest/ppa -y
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo add-apt-repository ppa:h-rayflood/llvm-upper -y
  - sudo apt-get update -qq
  - sudo apt-get install -y libmicrohttpd-dev libboost1.54-all-dev
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - if [ "$CXX" = "clang++" ]; then sudo apt-get install -qq clang-3.6; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.6" CC="clang-3.6"; fi

script:
  - cmake .
  - make
  - ./camrem_tests

after_success:
  - if [ "$COMPILER" = "g++-4.9" ]; then coveralls --exclude tests/tests.cpp --exclude src/libs/* --gcov-options '\-lp' --gcov 'gcov-4.9' ; fi
