language: cpp
sudo: true

matrix:
  fast_finish: true
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'boost-latest']
          packages: ['g++-4.9', 'libboost-test1.55-dev', 'libboost-filesystem1.55-dev', 'libboost-thread1.55-dev']
      before_install:
        - curl 'https://bintray.com/user/downloadSubjectPublicKey?username=netflixoss' | sudo apt-key add - 
        - echo "deb https://dl.bintray.com/netflixoss/ubuntu precise main" | sudo tee -a /etc/apt/sources.list
        - sudo apt-get update -qq
        - sudo apt-get install -y libmicrohttpd-dev libgphoto2-2-dev
      env: COMPILER=g++-4.9
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'boost-latest']
          packages: ['g++-5', 'libboost-test1.55-dev', 'libboost-filesystem1.55-dev', 'libboost-thread1.55-dev']
      before_install:
        - curl 'https://bintray.com/user/downloadSubjectPublicKey?username=netflixoss' | sudo apt-key add - 
        - echo "deb https://dl.bintray.com/netflixoss/ubuntu precise main" | sudo tee -a /etc/apt/sources.list
        - sudo apt-get update -qq
        - sudo apt-get install -y libmicrohttpd-dev libgphoto2-2-dev
      env: COMPILER=g++-5
    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.6', 'boost-latest']
          packages: ['clang-3.6', 'libboost-test1.55-dev', 'libboost-filesystem1.55-dev', 'libboost-thread1.55-dev']
      before_install:
        - curl 'https://bintray.com/user/downloadSubjectPublicKey?username=netflixoss' | sudo apt-key add - 
        - echo "deb https://dl.bintray.com/netflixoss/ubuntu precise main" | sudo tee -a /etc/apt/sources.list
        - sudo apt-get update -qq
        - sudo apt-get install -y libmicrohttpd-dev libgphoto2-2-dev
        - pip install --user git+git://github.com/eddyxu/cpp-coveralls.git
      env: COMPILER=clang++-3.6
    - os: osx
      compiler: clang
      before_install:
        - brew install libgphoto2
        - brew install libmicrohttpd
      env: COMPILER=clang++

script:
  - cmake . -DCMAKE_CXX_COMPILER=$COMPILER
  - make -j2
  - touch server.key
  - touch server.pem
  - ./camrem_unit_tests

after_success:
  - if [ "$COMPILER" = "clang++-3.6" ]; then make clean ; fi
  - if [ "$COMPILER" = "clang++-3.6" ]; then rm -rf CMakeFiles ; fi
  - if [ "$COMPILER" = "clang++-3.6" ]; then rm tests/temp.json tests/nonexistent.json ; fi
  - if [ "$COMPILER" = "clang++-3.6" ]; then pip install pyresttest ; fi
  - if [ "$COMPILER" = "clang++-3.6" ]; then cmake -DCOVERAGE=ON ; fi
  - if [ "$COMPILER" = "clang++-3.6" ]; then make -j2 all ; fi
  - if [ "$COMPILER" = "clang++-3.6" ]; then chmod +x .travis-coverages.sh ; fi
  - if [ "$COMPILER" = "clang++-3.6" ]; then ./.travis-coverages.sh ; fi
